ruby '2.2.3'
source 'https://rubygems.org'

gem 'envyable' # Should be loaded first in case other gems need ENV variables

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'

gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'active_model_serializers'
gem 'active_hash'
gem 'redis'
gem 'redis-namespace'
gem 'redis-session-store'
gem 'devise'
gem 'bcrypt', '~> 3.1.7'
gem 'lazy_high_charts'
gem 'wkhtmltopdf-binary'
gem 'pdfkit'
gem 'htmltoword'
gem 'kaminari'
gem 'kaminari-bootstrap'
gem 'devise_saml_authenticatable'
gem 'themes_on_rails'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'rails-controller-testing'
  gem 'faker'
  gem 'cucumber-rails', :require => false
  gem 'selenium-webdriver'
  gem 'database_cleaner'
  gem 'chromedriver-helper'
  gem 'capybara'
  gem 'poltergeist'
  gem 'phantomjs', :require => 'phantomjs/poltergeist'
  gem 'centurion'
end

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
